DROP TABLE IF EXISTS PAISOS;

CREATE TABLE PAISOS (
id_pais         smallint UNSIGNED NOT NULL AUTO_INCREMENT,
nom_pais        varchar(50) NOT NULL,
ISO_3166_2      varchar(2) NOT NULL,
ISO_3166_3      varchar(3) NOT NULL,
internetDomain  varchar(3) NULL,
    PRIMARY KEY (id_pais)
);


INSERT INTO PAISOS (id_pais,nom_pais,ISO_3166_2, ISO_3166_3, internetDomain) VALUES 
(default,'Islamic Republic of Afghanistan','AF','AFG','.af'),
(default,'Åland Islands','AX','ALA','.ax'),
(default,'Albania','AL','ALB','.al'),
(default,'Algeria','DZ','DZA','.dz'),
(default,'American Samoa','AS','ASM','.as'),
(default,'Andorra','AD','AND','.ad'),
(default,'Angola','AO','AGO','.ao'),
(default,'Anguilla','AI','AIA','.ai'),
(default,'Antarctica','AQ','ATA','.aq'),
(default,'Antigua and Barbuda','AG','ATG','.ag'),
(default,'Argentina','AR','ARG','.ar'),
(default,'Armenia','AM','ARM','.am'),
(default,'Aruba','AW','ABW','.aw'),
(default,'Australia','AU','AUS','.au'),
(default,'Austria','AT','AUT','.at'),
(default,'Azerbaijan','AZ','AZE','.az'),
(default,'The Bahamas','BS','BHS','.bs'),
(default,'Bahrain','BH','BHR','.bh'),
(default,'Bangladesh','BD','BGD','.bd'),
(default,'Barbados','BB','BRB','.bb'),
(default,'Belarus','BY','BLR','.by'),
(default,'Belgium','BE','BEL','.be'),
(default,'Belize','BZ','BLZ','.bz'),
(default,'Benin','BJ','BEN','.bj'),
(default,'Bermuda','BM','BMU','.bm'),
(default,'Bhutan','BT','BTN','.bt'),
(default,'Bolivia Bolivia (Plurinational State of)','BO','BOL','.bo'),
(default,'Saba','BQ','BES','.bq'),
(default,'Bosnia and Herzegovina Bosnia and Herzegovina','BA','BIH','.ba'),
(default,'Botswana','BW','BWA','.bw'),
(default,'Bouvet Island Bouvet Island','BV','BVT',''),
(default,'Brazil','BR','BRA','.br'),
(default,'British Indian Ocean Territory','IO','IOT','.io'),
(default,'Brunei','BN','BRN','.bn'),
(default,'Bulgaria','BG','BGR','.bg'),
(default,'Burkina Faso','BF','BFA','.bf'),
(default,'Burundi','BI','BDI','.bi'),
(default,'Cape Verde','CV','CPV','.cv'),
(default,'Cambodia','KH','KHM','.kh'),
(default,'Cameroon','CM','CMR','.cm'),
(default,'Canada','CA','CAN','.ca'),
(default,'Cayman Islands','KY','CYM','.ky'),
(default,'Central African Republic','CF','CAF','.cf'),
(default,'Chad','TD','TCD','.td'),
(default,'Chile','CL','CHL','.cl'),
(default,'China','CN','CHN','.cn'),
(default,'Christmas Island','CX','CXR','.cx'),
(default,'Cocos (Keeling) Islands','CC','CCK','.cc'),
(default,'Colombia','CO','COL','.co'),
(default,'Comoros','KM','COM','.km'),
(default,'Democratic Republic of the Congo','CD','COD','.cd'),
(default,'Republic of the Congo','CG','COG','.cg'),
(default,'Cook Islands','CK','COK','.ck'),
(default,'Costa Rica','CR','CRI','.cr'),
(default,'Ivory Coast','CI','CIV','.ci'),
(default,'Croatia','HR','HRV','.hr'),
(default,'Cuba','CU','CUB','.cu'),
(default,'Curaçao','CW','CUW','.cw'),
(default,'Cyprus','CY','CYP','.cy'),
(default,'Czech Republic','CZ','CZE','.cz'),
(default,'Denmark','DK','DNK','.dk'),
(default,'Djibouti','DJ','DJI','.dj'),
(default,'Dominica','DM','DMA','.dm'),
(default,'Dominican Republic','DO','DOM','.do'),
(default,'Ecuador','EC','ECU','.ec'),
(default,'Egypt','EG','EGY','.eg'),
(default,'El Salvador','SV','SLV','.sv'),
(default,'Equatorial Guinea','GQ','GNQ','.gq'),
(default,'Eritrea','ER','ERI','.er'),
(default,'Estonia','EE','EST','.ee'),
(default,'Eswatini','SZ','SWZ','.sz'),
(default,'Ethiopia','ET','ETH','.et'),
(default,'Falkland Islands','FK','FLK','.fk'),
(default,'Faroe Islands','FO','FRO','.fo'),
(default,'Fiji','FJ','FJI','.fj'),
(default,'Finland','FI','FIN','.fi'),
(default,'France','FR','FRA','.fr'),
(default,'French Guiana','GF','GUF','.gf'),
(default,'French Polynesia','PF','PYF','.pf'),
(default,'French Southern and Antarctic Lands','TF','ATF','.tf'),
(default,'Gabon','GA','GAB','.ga'),
(default,'The Gambia','GM','GMB','.gm'),
(default,'Georgia','GE','GEO','.ge'),
(default,'Germany','DE','DEU','.de'),
(default,'Ghana','GH','GHA','.gh'),
(default,'Gibraltar','GI','GIB','.gi'),
(default,'Greece','GR','GRC','.gr'),
(default,'Greenland','GL','GRL','.gl'),
(default,'Grenada','GD','GRD','.gd'),
(default,'Guadeloupe','GP','GLP','.gp'),
(default,'Guam','GU','GUM','.gu'),
(default,'Guatemala','GT','GTM','.gt'),
(default,'Bailiwick of Guernsey','GG','GGY','.gg'),
(default,'Guinea','GN','GIN','.gn'),
(default,'Guinea-Bissau','GW','GNB','.gw'),
(default,'Guyana','GY','GUY','.gy'),
(default,'Haiti','HT','HTI','.ht'),
(default,'Heard Island and McDonald Islands','HM','HMD','.hm'),
(default,'Holy See','VA','VAT','.va'),
(default,'Honduras','HN','HND','.hn'),
(default,'Hong Kong','HK','HKG','.hk'),
(default,'Hungary','HU','HUN','.hu'),
(default,'Iceland','IS','ISL','.is'),
(default,'India','IN','IND','.in'),
(default,'Indonesia','ID','IDN','.id'),
(default,'Iran (Islamic Republic of)','IR','IRN','.ir'),
(default,'Iraq','IQ','IRQ','.iq'),
(default,'Republic of Ireland','IE','IRL','.ie'),
(default,'Isle of Man','IM','IMN','.im'),
(default,'Israel','IL','ISR','.il'),
(default,'Italy','IT','ITA','.it'),
(default,'Jamaica','JM','JAM','.jm'),
(default,'Japan','JP','JPN','.jp'),
(default,'Jersey','JE','JEY','.je'),
(default,'Jordan','JO','JOR','.jo'),
(default,'Kazakhstan','KZ','KAZ','.kz'),
(default,'Kenya','KE','KEN','.ke'),
(default,'Kiribati','KI','KIR','.ki'),
(default,'North Korea Korea','KP','PRK','.kp'),
(default,'South Korea Korea','KR','KOR','.kr'),
(default,'Kuwait','KW','KWT','.kw'),
(default,'Kyrgyzstan','KG','KGZ','.kg'),
(default,'Laos','LA','LAO','.la'),
(default,'Latvia','LV','LVA','.lv'),
(default,'Lebanon','LB','LBN','.lb'),
(default,'Lesotho','LS','LSO','.ls'),
(default,'Liberia','LR','LBR','.lr'),
(default,'Libya','LY','LBY','.ly'),
(default,'Liechtenstein','LI','LIE','.li'),
(default,'Lithuania','LT','LTU','.lt'),
(default,'Luxembourg','LU','LUX','.lu'),
(default,'Macau','MO','MAC','.mo'),
(default,'North Macedonia','MK','MKD','.mk'),
(default,'Madagascar','MG','MDG','.mg'),
(default,'Malawi','MW','MWI','.mw'),
(default,'Malaysia','MY','MYS','.my'),
(default,'Maldives','MV','MDV','.mv'),
(default,'Mali','ML','MLI','.ml'),
(default,'Malta','MT','MLT','.mt'),
(default,'Marshall Islands','MH','MHL','.mh'),
(default,'Martinique','MQ','MTQ','.mq'),
(default,'Mauritania','MR','MRT','.mr'),
(default,'Mauritius','MU','MUS','.mu'),
(default,'Mayotte','YT','MYT','.yt'),
(default,'Mexico','MX','MEX','.mx'),
(default,'Federated States of Micronesia','FM','FSM','.fm'),
(default,'Moldova','MD','MDA','.md'),
(default,'Monaco','MC','MCO','.mc'),
(default,'Mongolia','MN','MNG','.mn'),
(default,'Montenegro','ME','MNE','.me'),
(default,'Montserrat','MS','MSR','.ms'),
(default,'Morocco','MA','MAR','.ma'),
(default,'Mozambique','MZ','MOZ','.mz'),
(default,'Myanmar','MM','MMR','.mm'),
(default,'Namibia','NA','NAM','.na'),
(default,'Nauru','NR','NRU','.nr'),
(default,'Nepal','NP','NPL','.np'),
(default,'Netherlands','NL','NLD','.nl'),
(default,'New Caledonia','NC','NCL','.nc'),
(default,'New Zealand','NZ','NZL','.nz'),
(default,'Nicaragua','NI','NIC','.ni'),
(default,'Niger','NE','NER','.ne'),
(default,'Nigeria','NG','NGA','.ng'),
(default,'Niue','NU','NIU','.nu'),
(default,'Norfolk Island','NF','NFK','.nf'),
(default,'Northern Mariana Islands','MP','MNP','.mp'),
(default,'Norway','NO','NOR','.no'),
(default,'Oman','OM','OMN','.om'),
(default,'Pakistan','PK','PAK','.pk'),
(default,'Palau','PW','PLW','.pw'),
(default,'State of Palestine','PS','PSE','.ps'),
(default,'Panama','PA','PAN','.pa'),
(default,'Papua New Guinea','PG','PNG','.pg'),
(default,'Paraguay','PY','PRY','.py'),
(default,'Peru','PE','PER','.pe'),
(default,'Philippines','PH','PHL','.ph'),
(default,'Pitcairn Islands','PN','PCN','.pn'),
(default,'Poland','PL','POL','.pl'),
(default,'Portugal','PT','PRT','.pt'),
(default,'Puerto Rico','PR','PRI','.pr'),
(default,'Qatar','QA','QAT','.qa'),
(default,'Réunion','RE','REU','.re'),
(default,'Romania','RO','ROU','.ro'),
(default,'Russia','RU','RUS','.ru'),
(default,'Rwanda','RW','RWA','.rw'),
(default,'Saint Barthélemy','BL','BLM','.bl'),
(default,'Tristan da Cunha','SH','SHN','.sh'),
(default,'Saint Kitts and Nevis','KN','KNA','.kn'),
(default,'Saint Lucia','LC','LCA','.lc'),
(default,'Collectivity of Saint Martin','MF','MAF','.mf'),
(default,'Saint Pierre and Miquelon','PM','SPM','.pm'),
(default,'Saint Vincent and the Grenadines','VC','VCT','.vc'),
(default,'Samoa','WS','WSM','.ws'),
(default,'San Marino','SM','SMR','.sm'),
(default,'São Tomé and Príncipe','ST','STP','.st'),
(default,'Saudi Arabia','SA','SAU','.sa'),
(default,'Senegal','SN','SEN','.sn'),
(default,'Serbia','RS','SRB','.rs'),
(default,'Seychelles','SC','SYC','.sc'),
(default,'Sierra Leone','SL','SLE','.sl'),
(default,'Singapore','SG','SGP','.sg'),
(default,'Sint Maarten','SX','SXM','.sx'),
(default,'Slovakia','SK','SVK','.sk'),
(default,'Slovenia','SI','SVN','.si'),
(default,'Solomon Islands','SB','SLB','.sb'),
(default,'Somalia','SO','SOM','.so'),
(default,'South Africa','ZA','ZAF','.za'),
(default,'South Georgia and the South Sandwich Islands','GS','SGS','.gs'),
(default,'South Sudan','SS','SSD','.ss'),
(default,'Spain','ES','ESP','.es'),
(default,'Sri Lanka','LK','LKA','.lk'),
(default,'Sudan','SD','SDN','.sd'),
(default,'Suriname','SR','SUR','.sr'),
(default,'Jan Mayen','SJ','SJM',''),
(default,'Sweden','SE','SWE','.se'),
(default,'Switzerland','CH','CHE','.ch'),
(default,'Syria','SY','SYR','.sy'),
(default,'Taiwan','TW','TWN','.tw'),
(default,'Tajikistan','TJ','TJK','.tj'),
(default,'Tanzania','TZ','TZA','.tz'),
(default,'Thailand','TH','THA','.th'),
(default,'East Timor','TL','TLS','.tl'),
(default,'Togo','TG','TGO','.tg'),
(default,'Tokelau','TK','TKL','.tk'),
(default,'Tonga','TO','TON','.to'),
(default,'Trinidad and Tobago','TT','TTO','.tt'),
(default,'Tunisia','TN','TUN','.tn'),
(default,'Turkey','TR','TUR','.tr'),
(default,'Turkmenistan','TM','TKM','.tm'),
(default,'Turks and Caicos Islands','TC','TCA','.tc'),
(default,'Tuvalu','TV','TUV','.tv'),
(default,'Uganda','UG','UGA','.ug'),
(default,'Ukraine','UA','UKR','.ua'),
(default,'United Arab Emirates','AE','ARE','.ae'),
(default,'United Kingdom','GB','GBR','.gb'),
(default,'United States Minor Outlying Islands','UM','UMI',''),
(default,'United States of America','US','USA','.us'),
(default,'Uruguay','UY','URY','.uy'),
(default,'Uzbekistan','UZ','UZB','.uz'),
(default,'Vanuatu','VU','VUT','.vu'),
(default,'Venezuela','VE','VEN','.ve'),
(default,'Vietnam','VN','VNM','.vn'),
(default,'British Virgin Islands','VG','VGB','.vg'),
(default,'United States Virgin Islands','VI','VIR','.vi'),
(default,'Wallis and Futuna','WF','WLF','.wf'),
(default,'Western Sahara','EH','ESH',''),
(default,'Yemen','YE','YEM','.ye'),
(default,'Zambia','ZM','ZMB','.zm'),
(default,'Zimbabwe','ZW','ZWE','.zw');


